# Generated by Django 4.0 on 2021-12-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='inputData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wasteInputBOD', models.CharField(max_length=20)),
                ('wasteInputTSS', models.CharField(max_length=20)),
                ('wasteInputTN', models.CharField(max_length=20)),
                ('wasteInputTP', models.CharField(max_length=20)),
                ('wasteOutputBOD', models.CharField(max_length=20)),
                ('wasteOutputTSS', models.CharField(max_length=20)),
                ('wasteOutputTN', models.CharField(max_length=20)),
                ('wasteOutputTP', models.CharField(max_length=20)),
            ],
        ),
    ]
