# Generated by Django 4.0 on 2021-12-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wastedata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('wasteInputBOD', models.FloatField()),
                ('wasteInputTSS', models.FloatField()),
                ('wasteInputTN', models.FloatField()),
                ('wasteInputTP', models.FloatField()),
                ('wasteOutputBOD', models.FloatField()),
                ('wasteOutputTSS', models.FloatField()),
                ('wasteOutputTN', models.FloatField()),
                ('wasteOutputTP', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='inputData',
        ),
    ]
