# Generated by Django 4.0 on 2021-12-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_wastedata_delete_inputdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedata',
            name='wasteInputBOD',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteInputTN',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteInputTP',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteInputTSS',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteOutputBOD',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteOutputTN',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteOutputTP',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='wasteOutputTSS',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
