# Generated by Django 4.0 on 2021-12-09 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_wastedata_wasteinputbod_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedata',
            name='targetCOD',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastedata',
            name='targetTN',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastedata',
            name='targetTP',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
