# Generated by Django 4.0 on 2021-12-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_wastedata_targetcod_wastedata_targettn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedata',
            name='targetBOD',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
