# Generated by Django 4.0 on 2021-12-12 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0005_wastedata_targetbod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastedata',
            old_name='targetCOD',
            new_name='targetTSS',
        ),
    ]
