# Generated by Django 4.0 on 2021-12-13 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_rename_targetcod_wastedata_targettss'),
    ]

    operations = [
        migrations.CreateModel(
            name='Makechart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
