# Generated by Django 4.0 on 2021-12-13 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_makechart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Makechart',
        ),
    ]
