# Generated by Django 4.0 on 2021-12-15 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_wastedata_removebod_wastedata_removetn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedata',
            name='BODdecision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastedata',
            name='TNdecision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastedata',
            name='TPdecision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastedata',
            name='TSSdecision',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
