# Generated by Django 4.0 on 2021-12-15 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_wastedata_boddecision_wastedata_tndecision_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wastedata',
            name='BODdecision',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='TNdecision',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='TPdecision',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='wastedata',
            name='TSSdecision',
            field=models.BooleanField(),
        ),
    ]
