# Generated by Django 4.0 on 2021-12-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0011_alter_wastedata_boddecision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastedata',
            name='wasteInflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wastedata',
            name='wasteOutflow',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
    ]
